export const defaultRpcUrl = "http://127.0.0.1:8545";
export const defaultWorldAddress = "0xfDf868Ea710FfD8cd33b829c5AFf79eDd15EcD5f";
export const defaultPrivateKey =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

export const pantheonWorldAbi = [
  {
    type: "function",
    name: "pantheon__dig",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__forage",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__plant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "plantId", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__harvest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__water",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__tend",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__move",
    stateMutability: "nonpayable",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__movePath",
    stateMutability: "nonpayable",
    inputs: [
      { name: "xs", type: "int32[]" },
      { name: "ys", type: "int32[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__sleep",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__pickupObject",
    stateMutability: "nonpayable",
    inputs: [{ name: "objectId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__dropObject",
    stateMutability: "nonpayable",
    inputs: [
      { name: "objectId", type: "bytes32" },
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__resolveAction",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__setBankAgent",
    stateMutability: "nonpayable",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__setBankItemPrice",
    stateMutability: "nonpayable",
    inputs: [
      { name: "itemId", type: "bytes32" },
      { name: "buyPrice", type: "uint256" },
      { name: "sellPrice", type: "uint256" },
      { name: "buyMaxQuantity", type: "uint32" },
      { name: "sellMaxQuantity", type: "uint32" },
      { name: "validUntil", type: "uint64" },
      { name: "epoch", type: "uint32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__sellObjectsToBank",
    stateMutability: "nonpayable",
    inputs: [{ name: "objectIds", type: "bytes32[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__buyObjectsFromBank",
    stateMutability: "nonpayable",
    inputs: [
      { name: "itemId", type: "bytes32" },
      { name: "quantity", type: "uint32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pantheon__getLastForageResult",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "itemId", type: "bytes32" },
      { name: "amount", type: "uint32" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pantheon__getLastHarvestResult",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "itemId", type: "bytes32" },
      { name: "amount", type: "uint32" },
      { name: "rareItemId", type: "bytes32" },
      { name: "rareAmount", type: "uint32" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pantheon__getWorldObjectCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "count", type: "uint32" }],
  },
  {
    type: "function",
    name: "pantheon__getWorldObject",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint32" }],
    outputs: [
      { name: "objectId", type: "bytes32" },
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "itemId", type: "bytes32" },
      { name: "amount", type: "uint32" },
      { name: "spawnedBy", type: "address" },
      { name: "createdAt", type: "uint64" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pantheon__getPlayerInventory",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [
      { name: "maxWeight", type: "uint32" },
      { name: "slots", type: "uint8[]" },
      { name: "objectIds", type: "bytes32[]" },
      { name: "objectTypeIds", type: "bytes32[]" },
      { name: "itemIds", type: "bytes32[]" },
      { name: "amounts", type: "uint32[]" },
      { name: "weights", type: "uint32[]" },
    ],
  },
  {
    type: "function",
    name: "getStaticField",
    stateMutability: "view",
    inputs: [
      { name: "tableId", type: "bytes32" },
      { name: "keyTuple", type: "bytes32[]" },
      { name: "fieldIndex", type: "uint8" },
      { name: "fieldLayout", type: "bytes32" },
    ],
    outputs: [{ name: "data", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getDynamicField",
    stateMutability: "view",
    inputs: [
      { name: "tableId", type: "bytes32" },
      { name: "keyTuple", type: "bytes32[]" },
      { name: "fieldIndex", type: "uint8" },
    ],
    outputs: [{ name: "data", type: "bytes" }],
  },
] as const;
