import { defineWorld } from "@latticexyz/world";

export default defineWorld({
  namespace: "pantheon",
  tables: {
    PlayerState: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        energy: "uint32",
        maxEnergy: "uint32",
        lastMoveAt: "uint64",
        moveSpeed: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    TerrainState: {
      schema: {
        x: "int32",
        y: "int32",
        material: "bytes32",
        digDepth: "uint32",
        loosened: "bool",
      },
      key: ["x", "y"],
    },
    TerrainAdmin: {
      schema: {
        id: "bytes32",
        admin: "address",
        exists: "bool",
      },
      key: ["id"],
    },
    TerrainType: {
      schema: {
        terrainId: "bytes32",
        walkable: "bool",
        diggable: "bool",
        plantable: "bool",
        sleepModifier: "uint32",
        moveCost: "uint32",
        exists: "bool",
        label: "string",
      },
      key: ["terrainId"],
    },
    TerrainTile: {
      schema: {
        x: "int32",
        y: "int32",
        terrainId: "bytes32",
        biomeId: "bytes32",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    PlantState: {
      schema: {
        x: "int32",
        y: "int32",
        plantId: "bytes32",
        owner: "address",
        plantedAt: "uint64",
        stage: "uint8",
        health: "uint32",
        stress: "uint32",
        lastMaintainedAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    PlantType: {
      schema: {
        plantId: "bytes32",
        seedItemId: "bytes32",
        harvestItemId: "bytes32",
        growthSeconds: "uint64",
        baseYieldMin: "uint32",
        baseYieldMax: "uint32",
        maintenanceInterval: "uint64",
        idealMoistureMin: "uint32",
        idealMoistureMax: "uint32",
        fertilityNeed: "uint32",
        exists: "bool",
        label: "string",
      },
      key: ["plantId"],
    },
    PlantTerrainRule: {
      schema: {
        plantId: "bytes32",
        terrainId: "bytes32",
        allowed: "bool",
        growthModifier: "uint32",
        yieldBonus: "uint32",
        rareItemId: "bytes32",
        rareChance: "uint32",
        exists: "bool",
      },
      key: ["plantId", "terrainId"],
    },
    FarmTileState: {
      schema: {
        x: "int32",
        y: "int32",
        moisture: "uint32",
        fertility: "uint32",
        exhaustion: "uint32",
        lastMaintainedAt: "uint64",
        lastWateredAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    ItemType: {
      schema: {
        itemId: "bytes32",
        category: "bytes32",
        weight: "uint32",
        exists: "bool",
        label: "string",
      },
      key: ["itemId"],
    },
    ObjectType: {
      schema: {
        objectTypeId: "bytes32",
        itemId: "bytes32",
        category: "bytes32",
        weight: "uint32",
        grabbable: "bool",
        usable: "bool",
        exists: "bool",
        label: "string",
      },
      key: ["objectTypeId"],
    },
    PlayerInventory: {
      schema: {
        player: "address",
        slot: "uint8",
        objectId: "bytes32",
        exists: "bool",
      },
      key: ["player", "slot"],
    },
    PlayerInventoryCapacity: {
      schema: {
        player: "address",
        maxWeight: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    ObjectState: {
      schema: {
        objectId: "bytes32",
        objectTypeId: "bytes32",
        itemId: "bytes32",
        amount: "uint32",
        exists: "bool",
      },
      key: ["objectId"],
    },
    InventoryObject: {
      schema: {
        objectId: "bytes32",
        owner: "address",
        exists: "bool",
      },
      key: ["objectId"],
    },
    BankAgent: {
      schema: {
        id: "bytes32",
        agent: "address",
        exists: "bool",
      },
      key: ["id"],
    },
    AgentConfig: {
      schema: {
        id: "bytes32",
        inftContract: "address",
        exists: "bool",
      },
      key: ["id"],
    },
    AgentIdentity: {
      schema: {
        tokenId: "uint256",
        player: "address",
        owner: "address",
        executor: "address",
        active: "bool",
        publicName: "string",
        publicURI: "string",
      },
      key: ["tokenId"],
    },
    AgentPlayer: {
      schema: {
        player: "address",
        tokenId: "uint256",
        exists: "bool",
      },
      key: ["player"],
    },
    AgentPermission: {
      schema: {
        tokenId: "uint256",
        executor: "address",
        permissionBits: "uint256",
        expiresAt: "uint64",
        maxActionsPerEpoch: "uint32",
        maxCucSpendPerEpoch: "uint256",
        usedActions: "uint32",
        usedCucSpend: "uint256",
        epoch: "uint32",
        exists: "bool",
      },
      key: ["tokenId", "executor"],
    },
    AgentMemoryCount: {
      schema: {
        tokenId: "uint256",
        count: "uint32",
        exists: "bool",
      },
      key: ["tokenId"],
    },
    AgentMemoryDelta: {
      schema: {
        tokenId: "uint256",
        sequence: "uint32",
        executor: "address",
        deltaHash: "bytes32",
        action: "bytes32",
        createdAt: "uint64",
        exists: "bool",
        encryptedDeltaURI: "string",
      },
      key: ["tokenId", "sequence"],
    },
    AgentMemoryCheckpoint: {
      schema: {
        tokenId: "uint256",
        checkpointHash: "bytes32",
        memoryRoot: "bytes32",
        updatedBy: "address",
        updatedAt: "uint64",
        exists: "bool",
        encryptedCheckpointURI: "string",
      },
      key: ["tokenId"],
    },
    AgentNetworkEndpoint: {
      schema: {
        tokenId: "uint256",
        protocol: "bytes32",
        updatedBy: "address",
        updatedAt: "uint64",
        exists: "bool",
        endpoint: "string",
      },
      key: ["tokenId", "protocol"],
    },
    CucBalance: {
      schema: {
        account: "address",
        balance: "uint256",
        exists: "bool",
      },
      key: ["account"],
    },
    BankItemPrice: {
      schema: {
        itemId: "bytes32",
        buyPrice: "uint256",
        sellPrice: "uint256",
        buyMaxQuantity: "uint32",
        sellMaxQuantity: "uint32",
        validUntil: "uint64",
        epoch: "uint32",
        exists: "bool",
      },
      key: ["itemId"],
    },
    BankItemInventory: {
      schema: {
        itemId: "bytes32",
        quantity: "uint32",
        exists: "bool",
      },
      key: ["itemId"],
    },
    BankInventorySlot: {
      schema: {
        slot: "uint32",
        objectId: "bytes32",
        exists: "bool",
      },
      key: ["slot"],
    },
    BankObject: {
      schema: {
        objectId: "bytes32",
        slot: "uint32",
        exists: "bool",
      },
      key: ["objectId"],
    },
    BankInventoryCount: {
      schema: {
        id: "bytes32",
        count: "uint32",
        exists: "bool",
      },
      key: ["id"],
    },
    BankTradeCount: {
      schema: {
        id: "bytes32",
        count: "uint32",
        exists: "bool",
      },
      key: ["id"],
    },
    BankTradeReceipt: {
      schema: {
        tradeId: "uint32",
        player: "address",
        itemId: "bytes32",
        objectId: "bytes32",
        quantity: "uint32",
        unitPrice: "uint256",
        totalCuc: "uint256",
        isPlayerSale: "bool",
        epoch: "uint32",
        createdAt: "uint64",
        exists: "bool",
      },
      key: ["tradeId"],
    },
    WorldObject: {
      schema: {
        objectId: "bytes32",
        x: "int32",
        y: "int32",
        spawnedBy: "address",
        createdAt: "uint64",
        exists: "bool",
      },
      key: ["objectId"],
    },
    WorldObjectCount: {
      schema: {
        id: "bytes32",
        count: "uint32",
        exists: "bool",
      },
      key: ["id"],
    },
    ForageTable: {
      schema: {
        terrainId: "bytes32",
        tableId: "bytes32",
        baseChance: "uint32",
        exists: "bool",
      },
      key: ["terrainId"],
    },
    ForageLootSlot: {
      schema: {
        tableId: "bytes32",
        slot: "uint8",
        itemId: "bytes32",
        weight: "uint32",
        minAmount: "uint32",
        maxAmount: "uint32",
        enabled: "bool",
      },
      key: ["tableId", "slot"],
    },
    ForageState: {
      schema: {
        x: "int32",
        y: "int32",
        lastForagedAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    ForageNonce: {
      schema: {
        player: "address",
        value: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    LastForageResult: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        itemId: "bytes32",
        amount: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    LastHarvestResult: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        itemId: "bytes32",
        amount: "uint32",
        rareItemId: "bytes32",
        rareAmount: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    ActionLog: {
      schema: {
        player: "address",
        action: "bytes32",
        updatedAt: "uint64",
        message: "string",
      },
      key: ["player"],
    },
    PendingAction: {
      schema: {
        player: "address",
        action: "bytes32",
        readyAt: "uint64",
        x: "int32",
        y: "int32",
        value: "uint32",
        data: "bytes32",
        exists: "bool",
      },
      key: ["player"],
    },
    WorldTime: {
      schema: {
        id: "bytes32",
        startedAt: "uint64",
        dayLength: "uint64",
        exists: "bool",
      },
      key: ["id"],
    },
  },
});
