import { defineWorld } from "@latticexyz/world";

export default defineWorld({
  namespace: "pantheon",
  tables: {
    PlayerState: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        energy: "uint32",
        maxEnergy: "uint32",
        lastMoveAt: "uint64",
        moveSpeed: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    TerrainState: {
      schema: {
        x: "int32",
        y: "int32",
        material: "bytes32",
        digDepth: "uint32",
        loosened: "bool",
      },
      key: ["x", "y"],
    },
    TerrainAdmin: {
      schema: {
        id: "bytes32",
        admin: "address",
        exists: "bool",
      },
      key: ["id"],
    },
    TerrainType: {
      schema: {
        terrainId: "bytes32",
        walkable: "bool",
        diggable: "bool",
        plantable: "bool",
        sleepModifier: "uint32",
        moveCost: "uint32",
        exists: "bool",
        label: "string",
      },
      key: ["terrainId"],
    },
    TerrainTile: {
      schema: {
        x: "int32",
        y: "int32",
        terrainId: "bytes32",
        biomeId: "bytes32",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    PlantState: {
      schema: {
        x: "int32",
        y: "int32",
        plantId: "bytes32",
        owner: "address",
        plantedAt: "uint64",
        stage: "uint8",
        health: "uint32",
        stress: "uint32",
        lastMaintainedAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    PlantType: {
      schema: {
        plantId: "bytes32",
        seedItemId: "bytes32",
        harvestItemId: "bytes32",
        growthSeconds: "uint64",
        baseYieldMin: "uint32",
        baseYieldMax: "uint32",
        maintenanceInterval: "uint64",
        idealMoistureMin: "uint32",
        idealMoistureMax: "uint32",
        fertilityNeed: "uint32",
        exists: "bool",
        label: "string",
      },
      key: ["plantId"],
    },
    PlantTerrainRule: {
      schema: {
        plantId: "bytes32",
        terrainId: "bytes32",
        allowed: "bool",
        growthModifier: "uint32",
        yieldBonus: "uint32",
        rareItemId: "bytes32",
        rareChance: "uint32",
        exists: "bool",
      },
      key: ["plantId", "terrainId"],
    },
    FarmTileState: {
      schema: {
        x: "int32",
        y: "int32",
        moisture: "uint32",
        fertility: "uint32",
        exhaustion: "uint32",
        lastMaintainedAt: "uint64",
        lastWateredAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    ItemType: {
      schema: {
        itemId: "bytes32",
        category: "bytes32",
        exists: "bool",
        label: "string",
      },
      key: ["itemId"],
    },
    PlayerInventory: {
      schema: {
        player: "address",
        itemId: "bytes32",
        amount: "uint32",
        exists: "bool",
      },
      key: ["player", "itemId"],
    },
    WorldObject: {
      schema: {
        objectId: "bytes32",
        x: "int32",
        y: "int32",
        itemId: "bytes32",
        amount: "uint32",
        spawnedBy: "address",
        createdAt: "uint64",
        exists: "bool",
      },
      key: ["objectId"],
    },
    WorldObjectCount: {
      schema: {
        id: "bytes32",
        count: "uint32",
        exists: "bool",
      },
      key: ["id"],
    },
    ForageTable: {
      schema: {
        terrainId: "bytes32",
        tableId: "bytes32",
        baseChance: "uint32",
        exists: "bool",
      },
      key: ["terrainId"],
    },
    ForageLootSlot: {
      schema: {
        tableId: "bytes32",
        slot: "uint8",
        itemId: "bytes32",
        weight: "uint32",
        minAmount: "uint32",
        maxAmount: "uint32",
        enabled: "bool",
      },
      key: ["tableId", "slot"],
    },
    ForageState: {
      schema: {
        x: "int32",
        y: "int32",
        lastForagedAt: "uint64",
        exists: "bool",
      },
      key: ["x", "y"],
    },
    ForageNonce: {
      schema: {
        player: "address",
        value: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    LastForageResult: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        itemId: "bytes32",
        amount: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    LastHarvestResult: {
      schema: {
        player: "address",
        x: "int32",
        y: "int32",
        itemId: "bytes32",
        amount: "uint32",
        rareItemId: "bytes32",
        rareAmount: "uint32",
        exists: "bool",
      },
      key: ["player"],
    },
    ActionLog: {
      schema: {
        player: "address",
        action: "bytes32",
        updatedAt: "uint64",
        message: "string",
      },
      key: ["player"],
    },
    PendingAction: {
      schema: {
        player: "address",
        action: "bytes32",
        readyAt: "uint64",
        x: "int32",
        y: "int32",
        value: "uint32",
        data: "bytes32",
        exists: "bool",
      },
      key: ["player"],
    },
    WorldTime: {
      schema: {
        id: "bytes32",
        startedAt: "uint64",
        dayLength: "uint64",
        exists: "bool",
      },
      key: ["id"],
    },
  },
});
