export type PlantDefinition = {
  id: string;
  kind: "crop" | "tree";
  seedId: string;
  seedLabel: string;
  label: string;
  harvestLabel: string;
  growthSeconds: number;
  growthThresholds: {
    seed: number;
    growing: number;
  };
  visualScale: number;
  footprint: {
    width: number;
    height: number;
  };
  plantWeight: number;
  harvestWeight: number;
  colors: {
    seed: number;
    growing: number;
    grown: number;
    fetched: number;
  };
};

export const plantDefinitions: Record<string, PlantDefinition> = {
  sungrain: {
    id: "sungrain",
    kind: "crop",
    seedId: "sungrain_seed",
    seedLabel: "Sungrain seed",
    label: "Sungrain",
    harvestLabel: "Sungrain sheaf",
    growthSeconds: 24,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0xd8a541,
      growing: 0x7dbd47,
      grown: 0xf0c85a,
      fetched: 0x8b7350,
    },
  },
  emberwheat: {
    id: "emberwheat",
    kind: "crop",
    seedId: "emberwheat_seed",
    seedLabel: "Emberwheat seed",
    label: "Emberwheat",
    harvestLabel: "Emberwheat sheaf",
    growthSeconds: 30,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0xc66a32,
      growing: 0x83a84a,
      grown: 0xf08a3e,
      fetched: 0x8b4f36,
    },
  },
  frostbarley: {
    id: "frostbarley",
    kind: "crop",
    seedId: "frostbarley_seed",
    seedLabel: "Frostbarley seed",
    label: "Frostbarley",
    harvestLabel: "Frostbarley sheaf",
    growthSeconds: 34,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0xcfe8f5,
      growing: 0x9ecfb7,
      grown: 0xe8f6ff,
      fetched: 0x8aa9b2,
    },
  },
  duskmillet: {
    id: "duskmillet",
    kind: "crop",
    seedId: "duskmillet_seed",
    seedLabel: "Duskmillet seed",
    label: "Duskmillet",
    harvestLabel: "Duskmillet bundle",
    growthSeconds: 28,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0x8b6fba,
      growing: 0x6f9b6a,
      grown: 0xb895d6,
      fetched: 0x5e536f,
    },
  },
  starrye: {
    id: "starrye",
    kind: "crop",
    seedId: "starrye_seed",
    seedLabel: "Starrye seed",
    label: "Starrye",
    harvestLabel: "Starrye bundle",
    growthSeconds: 38,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0xf2df8a,
      growing: 0x7fbf8f,
      grown: 0xfff0a8,
      fetched: 0x9a875a,
    },
  },
  silveroat: {
    id: "silveroat",
    kind: "crop",
    seedId: "silveroat_seed",
    seedLabel: "Silveroat seed",
    label: "Silveroat",
    harvestLabel: "Silveroat sheaf",
    growthSeconds: 32,
    growthThresholds: { seed: 0.25, growing: 1 },
    visualScale: 1,
    footprint: { width: 92, height: 92 },
    plantWeight: 0.08,
    harvestWeight: 0.35,
    colors: {
      seed: 0xbfc7c8,
      growing: 0x8fbf8d,
      grown: 0xd8ded7,
      fetched: 0x7d8582,
    },
  },
  applewood: {
    id: "applewood",
    kind: "tree",
    seedId: "applewood_seed",
    seedLabel: "Applewood seed",
    label: "Applewood",
    harvestLabel: "Applewood apples",
    growthSeconds: 72,
    growthThresholds: { seed: 0.18, growing: 1 },
    visualScale: 2,
    footprint: { width: 132, height: 132 },
    plantWeight: 1.4,
    harvestWeight: 0.55,
    colors: {
      seed: 0x9b6b33,
      growing: 0x6fb35b,
      grown: 0x4f9a49,
      fetched: 0x7d5a3b,
    },
  },
  pinecrest: {
    id: "pinecrest",
    kind: "tree",
    seedId: "pinecrest_seed",
    seedLabel: "Pinecrest cone",
    label: "Pinecrest",
    harvestLabel: "Pinecrest cones",
    growthSeconds: 84,
    growthThresholds: { seed: 0.18, growing: 1 },
    visualScale: 2.08,
    footprint: { width: 126, height: 146 },
    plantWeight: 1.7,
    harvestWeight: 0.48,
    colors: {
      seed: 0x8a5f37,
      growing: 0x486f42,
      grown: 0x2f5f3f,
      fetched: 0x6a5138,
    },
  },
  mapleflare: {
    id: "mapleflare",
    kind: "tree",
    seedId: "mapleflare_seed",
    seedLabel: "Mapleflare seed",
    label: "Mapleflare",
    harvestLabel: "Mapleflare leaves",
    growthSeconds: 90,
    growthThresholds: { seed: 0.18, growing: 1 },
    visualScale: 2.08,
    footprint: { width: 138, height: 138 },
    plantWeight: 1.6,
    harvestWeight: 0.5,
    colors: {
      seed: 0xb97338,
      growing: 0x879d45,
      grown: 0xd96b3a,
      fetched: 0x8f5a36,
    },
  },
  willowshade: {
    id: "willowshade",
    kind: "tree",
    seedId: "willowshade_seed",
    seedLabel: "Willowshade seed",
    label: "Willowshade",
    harvestLabel: "Willowshade fronds",
    growthSeconds: 96,
    growthThresholds: { seed: 0.18, growing: 1 },
    visualScale: 2.14,
    footprint: { width: 146, height: 146 },
    plantWeight: 1.45,
    harvestWeight: 0.42,
    colors: {
      seed: 0xb8c68f,
      growing: 0x7fb68f,
      grown: 0x6fa586,
      fetched: 0x6c806a,
    },
  },
  ironbark: {
    id: "ironbark",
    kind: "tree",
    seedId: "ironbark_seed",
    seedLabel: "Ironbark nut",
    label: "Ironbark",
    harvestLabel: "Ironbark nuts",
    growthSeconds: 110,
    growthThresholds: { seed: 0.16, growing: 1 },
    visualScale: 2.1,
    footprint: { width: 136, height: 142 },
    plantWeight: 2.2,
    harvestWeight: 0.72,
    colors: {
      seed: 0x5d5548,
      growing: 0x5d7355,
      grown: 0x4f5e4c,
      fetched: 0x45423d,
    },
  },
  honeyfig: {
    id: "honeyfig",
    kind: "tree",
    seedId: "honeyfig_seed",
    seedLabel: "Honeyfig seed",
    label: "Honeyfig",
    harvestLabel: "Honeyfigs",
    growthSeconds: 104,
    growthThresholds: { seed: 0.17, growing: 1 },
    visualScale: 2.05,
    footprint: { width: 140, height: 136 },
    plantWeight: 1.55,
    harvestWeight: 0.62,
    colors: {
      seed: 0xc49a4e,
      growing: 0x6fa864,
      grown: 0x7a9b45,
      fetched: 0x8a6a3c,
    },
  },
  frostpine: {
    id: "frostpine",
    kind: "tree",
    seedId: "frostpine_seed",
    seedLabel: "Frostpine cone",
    label: "Frostpine",
    harvestLabel: "Frostpine cones",
    growthSeconds: 132,
    growthThresholds: { seed: 0.15, growing: 1 },
    visualScale: 2.18,
    footprint: { width: 142, height: 154 },
    plantWeight: 1.9,
    harvestWeight: 0.66,
    colors: {
      seed: 0xb7d9e8,
      growing: 0x8bbbc0,
      grown: 0xd9f5ff,
      fetched: 0x7fa0ad,
    },
  },
  emberoak: {
    id: "emberoak",
    kind: "tree",
    seedId: "emberoak_seed",
    seedLabel: "Emberoak acorn",
    label: "Emberoak",
    harvestLabel: "Emberoak acorns",
    growthSeconds: 140,
    growthThresholds: { seed: 0.15, growing: 1 },
    visualScale: 2.2,
    footprint: { width: 150, height: 150 },
    plantWeight: 2,
    harvestWeight: 0.78,
    colors: {
      seed: 0xd07a3c,
      growing: 0x6e8d4a,
      grown: 0xe47a35,
      fetched: 0x7d4634,
    },
  },
  moonwillow: {
    id: "moonwillow",
    kind: "tree",
    seedId: "moonwillow_seed",
    seedLabel: "Moonwillow pearlseed",
    label: "Moonwillow",
    harvestLabel: "Moonwillow fronds",
    growthSeconds: 150,
    growthThresholds: { seed: 0.14, growing: 1 },
    visualScale: 2.22,
    footprint: { width: 156, height: 156 },
    plantWeight: 1.65,
    harvestWeight: 0.58,
    colors: {
      seed: 0xd8d8f1,
      growing: 0xaeb7d8,
      grown: 0xdcd7ff,
      fetched: 0x898aa8,
    },
  },
  starblossom: {
    id: "starblossom",
    kind: "tree",
    seedId: "starblossom_seed",
    seedLabel: "Starblossom seed",
    label: "Starblossom",
    harvestLabel: "Starblossom fruit",
    growthSeconds: 168,
    growthThresholds: { seed: 0.12, growing: 1 },
    visualScale: 2.25,
    footprint: { width: 164, height: 164 },
    plantWeight: 1.8,
    harvestWeight: 0.7,
    colors: {
      seed: 0xf2de83,
      growing: 0x8870b6,
      grown: 0xd8b4ff,
      fetched: 0x5f4c8a,
    },
  },
};

export function getPlantBySeed(seedId: string): PlantDefinition | undefined {
  return Object.values(plantDefinitions).find(
    (definition) => definition.seedId === seedId,
  );
}
